I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 61, in script call
    call WinCheck
  File "game/script.rpy", line 229, in script
    if palyer2win:
  File "game/script.rpy", line 229, in <module>
    if palyer2win:
NameError: name 'palyer2win' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 61, in script call
    call WinCheck
  File "game/script.rpy", line 229, in script
    if palyer2win:
  File "D:\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "D:\renpy-7.3.5-sdk\renpy\python.py", line 2084, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-7.3.5-sdk\renpy\python.py", line 2077, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 229, in <module>
    if palyer2win:
NameError: name 'palyer2win' is not defined

Windows-8-6.2.9200
Ren'Py 7.4.0.84
Krestiki_Noliki 1.0
Fri May 29 17:07:40 2020
